### ISSUE TITLE
Slots missing for LED holder

### ISSUE THREAD

**Issue by gniezen** [BioHackAcademy/BHA_Spectrophotometer#2]
In the current `Spectrometer-Lasercut.svg`, the two slots for sliding the LED holder into place seems to be missing?

**Comment by jcnossen** [comment]
Hmm sorry about that. I remember fixing that earlier but for some reason I
reverted and never committed the fix.
Fixed now. I've given write access to the spectrometer github to all 2015
team members, so you can also commit yourself if there are more problems.

cheers, Jelmer
